### ISSUE TITLE
Thanks!

### ISSUE THREAD

**Issue by ostark** [dyerc/craft-flux#1]
🙏🏼 Finally a useful plugin with tests in the Craft plugin store.

Thanks! That's all.

**Comment by dyerc** [comment]
Thank you! Really appreciate you taking the time to comment. I hope it's useful for you.

If you have any feedback on how Flux could be improved please don't hesitate to drop me an email.

**Comment by ostark** [comment]
I left the comment because 95% of all Craft plugins don't have any test and it bugs me.
I'll give it a spin at some point, but I'm not a potential consumer as I don't build websites :-)
