### ISSUE TITLE
CloudFront invalidations are limited to 3000 concurrent invalidation paths

### ISSUE THREAD

**Issue by markdrzy** [dyerc/craft-flux#11]
Per the [CloudFront API documentation](https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/Invalidation.html#InvalidationLimits),

> you can have invalidation requests for up to 3,000 files per distribution in progress at one time.

If this number is exceeded, the invalidation requests will fail. The [`invalidateCache`](https://github.com/dyerc/craft-flux/blob/v4/src/services/Cloudfront.php#L200) method accepts an array of paths, but does not presently batch the invalidation requests if greater than 3000 paths are provided. To work around this limitation, invalidation requests should be sent in 3000-chunk batches.

It should also be noted that invalidation requests may be in progress for a non-trivial duration; if multiple 3000-chunk invalidation requests are sent simultaneously, only the first batch will succeed — the others will fail. I believe the only way to avoid this situation is to send these invalidation requests synchronously.

**Comment by dyerc** [comment]
Thanks @markdrzy for pointing out both of these CloudFront request limits. I'll change the function to batch up the requests.
