### ISSUE TITLE
Flux doesn't correctly handle updated assets when the filename remains the same

### ISSUE THREAD

**Issue by markdrzy** [dyerc/craft-flux#12]
We have a site that imports real estate listings daily (using the [Feed Me](https://github.com/craftcms/feed-me/) plugin). Each imported listing has a list of associated images, which we are saving as assets in Craft. The API we are pulling these images from always names the associated images in the following pattern: `{locationId}-{index}.jpg`. If images are added, removed, or modified, the filenames will change accordingly. For example if we had the following list of images:

```
20220316-1.jpg
20220316-2.jpg
20220316-3.jpg
```

and the second image (`20220316-2.jpg`) was removed, the resulting list would look like this:

```
20220316-1.jpg
20220316-2.jpg
```

The image that _was_ `20220316-3.jpg` is now named `20220316-2.jpg`. When the import takes place, Craft removes the `20220316-3.jpg` asset, and replaces the file on the `20220316-2.jpg` asset with the file that was previously `20220316-3.jpg`.

When the asset is modified, Flux is correctly purging _transforms_ for this asset. However, Flux does not remove the _copy_ it makes of the original asset. Since Flux bases its transforms off of the _copy_, all transforms recreated after the purge are of the original `20220316-2.jpg` image, not the updated version.

We believe that this is due to the following check in Flux's S3 service ([line 243](https://github.com/dyerc/craft-flux/blob/develop/src/services/S3.php#L243C1-L245C10)):

```php
if (!is_a($asset->volume->fs, "craft\\awss3\\Fs") && $originalPath != $path) {
    $deleteObjects[] = $path;
}
```

Since we store our Flux transforms in an S3 volume the `is_a(… awsss3\\Fs")` check will return true, preventing Flux from purging it's _copy_ of the original asset file. It appears that double-checking that this is an S3 volume is unnecessary, and that the `$originalPath != $path` check is sufficient to prevent Flux from inadvertently removing the original asset.

Perhaps we are wrong in this assessment for other potential Flux configurations, but in our case, removing the S3 volume check like so:

```php
if ($originalPath != $path) {
    $deleteObjects[] = $path;
}
```

resolved our issue. Now the Flux _copy_ of the asset file is being purged, and the new asset file is used for all new transforms.

**Comment by dyerc** [comment]
Thanks for doing so much investigation around this @markdrzy. I think I added the `is_a` S3 check as an additional insurance measure against deleting the original asset which would be a worst case scenario.

I've just been trying to test and figure out any possibility for the original asset to be deleted but I think there are enough checks in place that this can't happen.

**Comment by markdrzy** [comment]
Thanks for addressing this issue, @dyerc! It looks like the fix has been applied to the develop branch — do you have any idea when you'll be putting this in an official release?

**Comment by dyerc** [comment]
> Thanks for addressing this issue, @dyerc! It looks like the fix has been applied to the develop branch — do you have any idea when you'll be putting this in an official release?

Hi @markdrzy, sorry I totally overlooked this and thought I had released a new stable version including this fix. I will get a new release out tomorrow.

**Comment by markdrzy** [comment]
Many thanks, Chris!
