### ISSUE TITLE
cacheEnabled/cachedEnabled set via "General Settings" -> "Cached Original Assets"

### ISSUE THREAD

**Issue by jmariklecr** [dyerc/craft-flux#15]
Sorry to create a second, concurrent issue, but this is entirely unrelated to the other one.  We've recently had an unreproducible issue with a client where assets were blurred when transformed.  I suspect there's something else entirely causing that issue, but it led me to find the **Cached Original Assets** setting.  We use AWS for our primary assets, so it doesn't make sense for us to have this setting enabled, and the core issue was the result of the full res copy ending up being <10 KB in size.  This was then used in the transforms resulting in the blurred images.

In attempting to bypass this step, I tried setting the "Cached Original Assets" to false.  Unfortunately, it didn't seem to have any affect.  I noticed the full res copies were still being created in the flux prefix directory.

After some digging I found that the variable is called cacheEnabled on the PHP side but it's cache**d**Enabled on the javascript side (with an extra letter "d").  The javascript is built and compressed, so I was comfortable replacing the variable and running the install, but I dare not create a PR.  I was able to confirm that after that change, it no longer created the full res copies, so I know the fix works.

Sorry I can't provide a specific place, but I'm pretty sure cachedEnabled is only referenced and used in one place in the response index.js.

**Comment by dyerc** [comment]
Thanks very much for spotting this @jmariklecr . This was easily fixed in the attached commit above.

When the source Craft filesystem is the same S3 bucket, Flux should ignore this setting completely and never make cached copies. Even with the misspelling, this should be working correctly and is based on the source type:

https://github.com/dyerc/craft-flux/blob/dc1b48e3716b5d43611f973ea6231ea1f1c73f94/lambda/inc/processor.ts#L34-L35

Is it the same S3 bucket used for storing the primary assets and storing the transformed versions? If so, can I just confirm, if you look at the compiled source for your viewer request function. Does the configuration list a type of local such as the following:

```
"sources":[{"type":"local","handle":"fsHandle","region":"..."}]
```

If the `type` is `local` the Lambda image processor should directly try to read the source file.

Let me know on the above and we can hopefully get to the bottom of what's happening.

**Comment by jmariklecr** [comment]
I feel so foolish. :P I didn't realize the repo had the lamda source in a pre-built format! I could have provided much better details if I realized that.

You're correct about the type not being "local".  For us it shows "remote" even though it's the same bucket, but I think I've found where the root issue is.

https://github.com/dyerc/craft-flux/blob/dc1b48e3716b5d43611f973ea6231ea1f1c73f94/src/models/SettingsModel.php#L154-L172

`is_a($volume->fs, "craft\\awss3\\Fs")` returns true, but `$volume->fs->settings['bucket'] == App::parseEnv($this->awsBucket)` returns false.  I decided to `Craft::dd()` the variables to see what the issue is.  Here's what we have (bucket name is replaced for security reasons):

```
array:4 [▼
  "$volume->fs->settings["bucket"]" => "$S3_BUCKET"
  "App::parseEnv($this->awsBucket)" => "our-clients-bucket-name"
  "$this->awsBucket" => "$S3_BUCKET"
  "App::parseEnv($volume->fs->settings["bucket"])" => "our-clients-bucket-name"
]
```

It looks like the craft\awss3\Fs class doesn't return the actual bucket value.  It returns whatever the setting is, which in our case is an environment variable.  I'm guessing `$volume->fs->settings["bucket"]` needs to be wrapped in `App::parseEnv()`.  That's how the original class appears to interact with the bucket property too:

https://github.com/craftcms/aws-s3/blob/a160e2247c9fb16eacb4131b8310088fad33ebfd/src/Fs.php#L292-L300

**Comment by dyerc** [comment]
Thanks so much for investigating this @jmariklecr. It all makes perfect sense why you were experiencing the incorrect behaviour.

Please could you have a try with version 5.0.3 which includes the referenced commit. Let me know if this resolves the problem and I can close this issue.

**Comment by jmariklecr** [comment]
Thank you so much, Chris! I've confirmed that both the function install change and the fix for detecting s3 based filesystems work for our Craft 4 site.  Full res copies are no longer being created in the flux prefix directory of the bucket.  I'm closing this issue.  I'll close #14 after we have a chance to test the version 5.0.3 changes on one of our Craft 5 sites.

Thank you for your work on this!
