### ISSUE TITLE
Settings validation fails

### ISSUE THREAD

**Issue by markdrzy** [dyerc/craft-flux#5]
Settings validation fails for AWS Resource Prefix (awsResourcePrefix) and S3 Root Prefix (rootPrefix) when using environment variables.

Fixed in PR #4

**Comment by dyerc** [comment]
Thanks very much for submitting a PR to fix this @markdrzy, much appreciated!

**Comment by markdrzy** [comment]
Very happy to help out, @dyerc!  We really appreciate your work — this is a huge improvement for many of our image-heavy sites.

Apologies for forgetting the import in my PR — somehow I failed to commit that line before I submitted it.

Do you have an ETA on when you plan to release a new version of the plugin with this fix implemented?

**Comment by dyerc** [comment]
That's great, I'm really pleased to hear Flux is improving the performance of your sites! If you have any feature suggestions for future versions please let me know.

I have just released version 4.1.4 which incorporates your PR.
