### ISSUE TITLE
Multiple Flux-enabled sites on one AWS account eventually exceeds Cache Policy and Origin Request Policy quotas

### ISSUE THREAD

**Issue by markdrzy** [dyerc/craft-flux#8]
The quantity of Cache Policies and Origin Request Policies are strictly limited to 20 (each) per AWS account. AWS does not provide a means to alter the quota for these resources. If you manage multiple Flux-enabled projects under one AWS account, you run the risk of exceeding your quota.

My agency ran into this issue recently upon the creation of our 10th Flux-enabled project. We maintain two environments per project: staging and production. Since we'd already had other custom Cache and Origin Request Policies on our AWS account, our 10th project put us over the 20 policy limit.

All that to say: thank you for this plugin — it was a lifesaver for us, and we are including it on all of our larger projects going forward. Keep up the good work!

**Comment by dyerc** [comment]
Hi @markdrzy , apologies this has taken me a couple of weeks to get sorted. In the slight variation we discussed in PR #9 I have implemented a strict naming option. I have made the default false, so Flux will use the same cache and origin request policies for all sites in the account. This gets updated each time any site is installed although it should be the same content. It might be cleaner to make it only do this if required in future, but I think that's something for another day.

Would you mind giving the development version a quick test for me and I will cut a new release next week.

Hope you don't mind me not merging your PR exactly as is, but I just felt doing it this way makes everything slightly simpler for users who don't want to get into the complexities of Flux and AWS.

**Comment by markdrzy** [comment]
Hey @dyerc - Sorry for the delay, but I should be able to test out the development version this week. I'll let you know if I run into any issues. Thanks!

**Comment by markdrzy** [comment]
@dyerc - We have been using the `dev-develop` branch in production and it has behaved as expected. As far as I'm concerned I think it's good to release. Let me know if you have any concerns or want to discuss further.
